<?php
/**
 * @file
 * Code for the com_gallery feature.
 */

include_once 'com_gallery.features.inc';

function com_gallery_init() {
	$path = drupal_get_path('module', 'com_gallery');
	
	drupal_add_js($path .'/js/jquery.infinitescroll.min.js');
 	drupal_add_js($path .'/js/masonry.pkgd.min.js');
  drupal_add_js($path .'/js/com_gallery.js');
}


function com_gallery_registry_alter(&$theme_registry) {
  // tell the theme system to look in the "templates" subdirectory within our module directory
  $module_path = drupal_get_path('module', 'com_gallery');
  $theme_registry['search_results']['theme paths'] = array(0 => $module_path . '/templates');
  $theme_registry['search_results']['theme path'] = $module_path . '/templates';
  $theme_registry['search_results']['path'] = $module_path . '/templates';
  // tell the theme system to use 'search-results.tpl.php' as the template file. Note that you do not include 'tpl.php'
  $theme_registry['search_results']['template'] = 'search-results';
}



